apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: argocd-namespace-operator-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
status:
  loadBalancer: {}
